### PR TITLE
Add the ability for users to support different tokens for different requests

### PR DESCRIPTION
**Pull request by jsand-minimal**
The user can modify the Rack::Request object to change the token on a per-request basis
```
Rack::Request.new(env).update_param('wovn_token', 'test1')
```

I will add and fix the tests!!

### Purpose/goal of Pull Request (Issue #)
This is for cloud CMS services who want to be able to load a token per user based on which website they are serving.

### CODE REVIEW

**Comment by jsand-minimal** [comment]
https://www.notion.so/wovnio/Dynamic-tokens-in-WOVNrb-30ba652b5a9343f2ae1746f210e08835

**Comment by mrasu** [comment]
closure is more flexible than request parameter
If closure is used, developer can change token inside existing Rails, but if only request parameter, user need to change nginx or other frontend servers

**Comment by jsand-minimal** [comment]
The request object is a Rack object that is used for passing information between Rack middleware. The user needs to modify the object inside of their rack application (for example, RoR).

**Comment by jsand-minimal** [comment]
I'll do it as a closure, if we agree that's the right choice. Here was my reasoning:

I wanted to do the simplest solution that follows best practices for rack middleware. When I looked it up, I couldn't find a "best practice" but every resource I found said to modify the Rack::Request object to communicate between rack middleware.

Thoughts? I don't care, as long as it's a good solution. I'm waiting for an answer before fixing the tests because if I do it with a closure my current test problem disappears.

**Comment by mrasu** [comment]
ok, I misunderstand. closure and Rack is almost same. I will agree the resources

**Comment by hythof** [comment]
Almost okay for me.
If the test is passes, I will approve of it.

**Pull request merged**
