### PR TITLE
Fix segmentation introduced with release 0.2.11.

### PR DESCRIPTION
**Pull request by a-bougouin**
### Purpose/goal of Pull Request (Issue #)
Related to:
- Segmentation fault when creating `wovn-src` comment node

### Comments
Creating a comment node needs to be done from the node's document instead
of the node itself.

### CODE REVIEW

**Comment by mrasu** [comment]
can you make a test?

**Comment by a-bougouin** [comment]
@mrasu done

**Comment by hythof** [comment]
I can't confirm this change effect.
If change to `Nokogiri::XML::Comment.new(node, "wovn-src:#{text}")` at  `lib/wovnrb/html_replacers/replacer_base.rb` line 21, but test is pass.

Could you tell me the details of this change?

**Comment by a-bougouin** [comment]
The problem is that using node leads to abort trap sometimes (some nodes can't be used to create comment nodes but Nokogiri does not handle it well and abort trap occurs), using node.document is more correct according to documentation of Nokogiri::XML:: Comment::new and does not fail.

**Comment by a-bougouin** [comment]
I am trying to reproduce abort trap on test

**Comment by a-bougouin** [comment]
@hythof to reproduce, you need to make sure you are running tests with same Nokogiri version than the issue (nokogiri 1.6.1)

**Comment by hythof** [comment]
@a-bougouin I was able to reproduce it.
Thanks.

**Comment by a-bougouin** [comment]
@hythof you can

**Comment by a-bougouin** [comment]
@hythof I added crashing test case on circle ci.

**Comment by hythof** [comment]
I confirmed fix.

**Pull request merged**
