### PR TITLE
(3.5.0) Add setting for disabling automatically inserting middleware. Change installation flow.

### PR DESCRIPTION
**Pull request by bstewart00**
### Purpose/goal of Pull Request (Issue #)
https://wovnio.atlassian.net/browse/SUP-713
### Comments
Major version bump -> 3.0.0
Allow disabling automatically inserting middleware. Users that need wovnrb in a specific order (e.g. for deflate) should insert it manually.

We were using private rails methods to try and do this automatically before (since there is no other way to check the middleware stack). These functions changed in Rails 6 which caused problems, and could happen again.

The default behavior is to always insert wovnrb as the first middleware. This is the same as before for any user that wasn't using Deflater.

**This means users upgrading to this version of wovnrb may need to make configuration changes.**

e.g. in `production.rb` where you do application initialization:
```
  config.middleware.use Rack::Deflater
  config.middleware.insert_after Rack::Deflater, Wovnrb::Interceptor

  config.wovnrb = {
    :project_token => 'EnS!t3',
    :default_lang => 'en',
    :supported_langs => ['en'],
    :url_pattern => 'path',
    :install_middleware => false
  }
```

If a user has middleware they need to run first, they can turn `install_middleware` off and be responsible for adding the `Wovnrb::Interceptor` middleware as needed. The main case is Deflater, which must be the first middleware to handle decompression so Wovnrb can see the normal HTML. But you could also imagine middleware that sets environment variables or disables wovnrb for certain requests.

### CODE REVIEW

**Comment by iwai-wovn** [comment]
The Rails guide mentions `config.middleware.insert_after`, which I think is a common solution for Rails users, so we might as well guide them to add it after Rack::Deflater as follows.
````
config.middleware.insert_after Rack::Deflater, Wovnrb::Interceptor
````
https://guides.rubyonrails.org/rails_on_rack.html#adding-a-middleware

**Comment by bstewart00** [comment]
> The Rails guide mentions `config.middleware.insert_after`, which I think is a common solution for Rails users, so we might as well guide them to add it after Rack::Deflater as follows.
> 
> ```
> config.middleware.insert_after Rack::Deflater, Wovnrb::Interceptor
> ```
> 
> [guides.rubyonrails.org/rails_on_rack.html#adding-a-middleware](https://guides.rubyonrails.org/rails_on_rack.html#adding-a-middleware)

of course. Just we cannot do this automatically for them.

**Comment by bstewart00** [comment]
`Rails.configuration.wovnrb` is also safe to use inside a Railtie, so I changed it to use this like the rest of the wovnrb settings.

**Comment by bstewart00** [comment]
Sinatra would not have been affected by this bug, since it doesn't use the Railtie. The user inserts the middleware manually already.

**Review by zeyuwu — APPROVED** [review]
Looks good and the README is very clear.

**Review by Soichiro725 — APPROVED** [review]
Looks good.

**Comment by bstewart00** [comment]
@iwai-wovn do you think these changes are OK?

**Review by iwai-wovn — APPROVED** [review]

**Pull request merged**
