### PR TITLE
	Add wovnrb.target_lang env to be used in user application

### PR DESCRIPTION
**Pull request by a-bougouin**
### Purpose/goal of Pull Request (Issue #)
Add a request env value to make visible the language detected by WovnRB: `wovnrb.target_lang`.

### Comments
Some users want to know the target language detected by WovnRB. This is now possible by looking at the `wovnrb.target_lang` value in the request environment that WovnRB sends to the application (`request.env['wovnrb.target_lang']`).

### CODE REVIEW

**Comment by mrasu** [comment]
is it common to set these type of information at env?

**Comment by a-bougouin** [comment]
@mrasu I did not find any good practice for what we want to do. I only saw $_ENV use to set development or production mode.

My assumption here is that WovnPHP is built around the use application, so in my opinion the language detected by WovnPHP can be considered as part of the application environment.

**Comment by a-bougouin** [comment]
@mrasu the environment is intended to be extended by rack middlewares, however I did not respect the naming convention (should be prefixed by 'wovnrb.'): http://www.rubydoc.info/github/rack/rack/master/file/SPEC

**Comment by a-bougouin** [comment]
I changed the name to 'wovnrb.target_lang' according to rack naming convention

**Comment by mrasu** [comment]
Sorry, I mean "common" is for the web like Node, Django, Cake or others.

**Comment by a-bougouin** [comment]
WovnRB is Rack middleware, seems normal to follow rack way.
@WOVNio/developers what do you think?

**Comment by a-bougouin** [comment]
In .NET, Node and Go (others probably), it is referred as request context and use for request-scoped data that transits processes and APIs.

**Comment by mrasu** [comment]
thanks

**Pull request merged**
