### PR TITLE
Use valid marker for input value

### PR DESCRIPTION
**Pull request by Soichiro725**
### Purpose/goal of Pull Request (Issue #)
https://github.com/WOVNio/equalizer/issues/24431

Before posting html to html-swapper, wovnrb put marker like `<!-- __wovn-backend-ignored-key-0 -->` to value attribute of input tag which type is hidden.
After response backed from html-swapper, this marker is replaced back to original.
But this marker is remained like `&lt;!-- __wovn-backend-ignored-key-0 --&gt;`, because of escaped.

I add `CGI.unescapeHTML` before revert marker.

### CODE REVIEW

**Comment by bstewart00** [comment]
what's doing the escaping?

**Comment by Soichiro725** [comment]
> what's doing the escaping?

I don't know, but recent html-swapper library update may have affected it.
I will check.

**Comment by bstewart00** [comment]
It's not actually valid to put a `<!-- -->` comment inside of a HTML attribute value, so i'm surprised we do this. I think it would be correct behaviour for Nokogiri to change the attribute to `&lt;` in that case.

I think the unescapeHTML fix is safe since when replacing whole nodes with the marker, the comment should come back unchanged, and we control the text inside it - `<!-- __wovn-backend-ignored-key-0 -->`.

An alternative would be to change ReplaceMarker for attributes to use a different marker, like `"__wovn-ignored-key-0"` without a comment.

This bug will need to be fixed on all backends though.

**Comment by Soichiro725** [comment]
> I don't agree with doing this though. This is unescaping the entire HTML, which could include escaped HTML from the user which should remain escaped.

I fixed.

**Comment by Soichiro725** [comment]
Thanks!

**Comment by bstewart00** [comment]
Do change the description and name though

**Pull request merged**
