### PR TITLE
Feature/fragmented values swapping

### PR DESCRIPTION
**Pull request by a-bougouin**
### Purpose/goal of PR (Issue #)
- Enable fragmented value swapping on Wovnrb.

### Comments
- Includes both sprint tasks of Hiroaki and I.

### Release comments (new feature, migrations, indexes)
- User must configure Wovnrb to use new scraping: `use_scraping2 = true`.
- This PR will have to use code added in https://github.com/WOVNio/wovnrb/pull/53 (once merged)

### CODE REVIEW

**Comment by jsand-minimal** [comment]
Why is this on hold?

**Comment by mrasu** [comment]
sorry, forgot

**Comment by jsand-minimal** [comment]
Please fix the conflicts!

**Comment by mrasu** [comment]
can close?

**Pull request closed without merging**
